# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 18:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import momo_api.account.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('jwt_secret_key', models.CharField(default=momo_api.account.models._generate_jwt_secret_key, editable=False, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('account_type', models.PositiveSmallIntegerField(choices=[(1, b'User'), (2, b'Company')], default=1)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('avatar', models.ImageField(blank=True, max_length=256, null=True, upload_to=b'')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'.", regex=b'^\\+?1?\\d{9,15}$')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('jwt_secret_key', models.CharField(default=momo_api.account.models._generate_jwt_secret_key, editable=False, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('account_type', models.PositiveSmallIntegerField(choices=[(1, b'User'), (2, b'Company')], default=1)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('avatar', models.ImageField(blank=True, max_length=256, null=True, upload_to=b'')),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'.", regex=b'^\\+?1?\\d{9,15}$')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
